### ISSUE TITLE
_helpers.scss

### ISSUE THREAD

**Issue by wfendler** [space150/spaceBase#26]
### Error?

I'm not sure I understand the purpose of this class.
https://github.com/space150/spaceBase/blob/master/scss/base/_helpers.scss#L89

``` scss
.nowrap { display: inline-block; }
```
### Upper vs. Caps

I also this one of @mckennedy's additions to a previous project would be a valuable addition:
https://github.com/space150/spaceBase/blob/master/scss/base/_helpers.scss#L86
From:

``` scss
.text--caps { text-transform: uppercase !important; }
```

To:

``` scss
.text--caps { text-transform: capitalize !important; }
.text--upper { text-transform: uppercase !important; }
```
### .hidden

Is this excessive here? Isn't `display: none;` sufficient? Or does `visibility: hidden` account for something I'm not aware of?
https://github.com/space150/spaceBase/blob/master/scss/base/_helpers.scss#L17-L21

``` scss
// Hide from screenreaders and browsers
.hidden {
  display: none;
  visibility: hidden;
}
```
### Class Names

If we want to go at this with a more BEM-like approach, then I would say we can change things like `float--right` to `float-right` since `float` isn't an object that's being extended with `--right`, it's more like it's own mini object. The same goes for the `text--` objects.
