### ISSUE TITLE
n-up mixin doesn't work with media queries

### ISSUE THREAD

**Issue by mckennedy** [space150/spaceBase#40]
``` scss
@include n-up(3);
@include media-query(hand-and-up) {
  @include n-up(4);
}
@include media-query(lap-and-up) {
  @include n-up(11);
}
```

Results in:

``` css
/* line 20, ../scss/base/_mixins.scss */
.pigments li:nth-child(3n + 1) {
  clear: left;
}
@media only screen and (min-width: 480px) {
  /* line 20, ../scss/base/_mixins.scss */
  .pigments li:nth-child(4n + 1) {
    clear: left;
  }
}
@media only screen and (min-width: 768px) {
  /* line 20, ../scss/base/_mixins.scss */
  .pigments li:nth-child(11n + 1) {
    clear: left;
  }
}
```

es no bueno. it's not overwriting previous clears and is clearing at all three breakpoints lap-and-up.
