### ISSUE TITLE
How about some table classes as helpers?

### ISSUE THREAD

**Issue by mckennedy** [space150/spaceBase#41]
I like the idea of (maybe in helpers)
```css
.table {
  display: table;
  width: 100%;
}

.row {
  display: table-row;
}

.cell {
  display: table-cell;
}
```
Manderson likes something more explicit like: `.display-table`, `.display-row`, `.display-cell`

thoughts?
