### ISSUE TITLE
Default heading font

### ISSUE THREAD

**Issue by athaeryn** [space150/spaceBase#43]
I think maybe there should be a variable for the heading font, which could be set by default to `$font-body`. `h1`-`h6` and `.h1`-`.h6` could be set to use this font, so that if/when you add a heading font they will use it.

So this is what I'm proposing:

```scss
$font-body: "Comic Sans";
$font-head: $font-body;

h1, .h1,
h2, .h2,
h3, .h3,
h4, .h4,
h5, .h5,
h6, .h6 {
  font-family: $font-head;
}
```
